### ISSUE TITLE
[Safari] justify-content: space-between; doesn't expand when content overflow

### ISSUE THREAD

**Issue by Flaburgan** [philipwalton/flexbugs#118]
Demo of the bug: http://codepen.io/anon/pen/YwQMoR

I'm not sure what the spec indicates, but I'm trying to create a sticky footer. That means I have
```html
<header></header>
<main></main>
<footer></footer>
```
Header and footer have fixed height. If header + main + footer height is < than <body> height (set to 100%), then the footer has to be fixed at the end of the page (as if it has `position: fixed; bottom: 0;`) but when the `<main>` element has a big height, then the footer has to be at the bottom of the page, invisible until the user scrolls.

In [the demo](http://codepen.io/anon/pen/xZrQRK) you can try to remove `<main>` content to see that the footer is correctly positioned when `<main>` is small. But when you add content, Safari still displays the content at the bottom of the page. Compare to Firefox to see the expected result.

**Comment by Flaburgan** [comment]
Code of the demo, just in case:

```html
<header>
  header
</header>
<main>main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main<br /><br />main</main>
<footer>footer</footer>
```

```css
html,
body {
  height: 100%;
}

body {
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-flex;
  display: -ms-flexbox;
  display: flex;
  
  -webkit-flex-flow: column;
  -moz-flex-flow: column;
  -ms-flex-flow: column;
  flex-flow: column;
  
  -webkit-box-pack: justify;
  -ms-flex-pack: justify;
  -webkit-justify-content: space-between;
  justify-content: space-between;
}

header,
main,
footer {
	padding: 12px;
	flex-basis: none;
}

header {
	background-color: #3388bb;
}

main {
	background-color: #8833bb;
	flex-basis: auto;
}

footer {
	background-color:#bb8833;
}
```
