### ISSUE TITLE
Misdescribed bug: "Inline elements are not treated as flex-items"

### ISSUE THREAD

**Issue by ruafozy** [philipwalton/flexbugs#123]
Bug 12, "Inline elements are not treated as flex-items", seems to be
misdescribed, at least for IE11.  With that browser, on Windows 7, if I open
up the workaround (12.1.b, at http://codepen.io/philipwalton/pen/NqLoNp) and
change `display: block` to `display: inline`, the bug doesn't strike and the
page is unchanged.

If I reload the page and add

  ```CSS
  .FlexContainer::before
  {
    display: inline;
  }
  ```

at the end of the CSS, the bug doesn't strike and the page is unchanged.
