### ISSUE TITLE
Min height issue with Chrome and IE11

### ISSUE THREAD

**Issue by skmasq** [philipwalton/flexbugs#144]
**[Update]**: #135 this actually solves the problem better, by setting `height: 0` instead of `height: 100%`

So here is a fun bug,

Chrome doesn't know how to calculate height if the min-height **is not** set, and IE doesn't know how to calculate height if the min-height property **is** set.

Code:
```less
.body-content {
    position: relative;
    float: left;
    padding: 0 @SD_General_SidePadding;
    // TODO: This fix is only because of JavaScript perfomring calculations on hight
    padding-bottom: @SD_Footer_height;
    width: 100%;
    overflow: auto;
    min-height: ~"calc(100vh - @{SD_Header_height})";

    .content-columns {
        display: table;
        width: 100%;
        min-height: ~"calc(100vh - @{SD_Header_height} - @{SD_Footer_height})";

        .content-columns-inner {
            #bundle #Flex .dispalyFlexbox();
            #bundle #Flex .flexboxDirection(row);
            // Notes: Different browsers calculate height differently. IE11 can't calculate min-height without table wrapper and other browsers can't caluclate height within table
            // Notes: This one is for IE11+
            height: 100%;
            // Notes: This one is for other browsers
            min-height: ~"calc(100vh - @{SD_Header_height} - @{SD_Footer_height})";
        }
    }
}
```

Solution:

```less
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    .body-content{
        .content-columns{
            .content-columns-inner{
                min-height: auto !important; // IE why u no know to calc height with min-height?
            }
        }
    }
}
```
