### ISSUE TITLE
iOS Nested Flex item percentage based height appears collapsed

### ISSUE THREAD

**Issue by ellm** [philipwalton/flexbugs#217]
Tested in both iOS Safari and Chrome.

The following markup and styles causes the bug.
Demo here: https://codepen.io/ellm/pen/vmgGPE

```html
<div class="flex-container">
  <div class="flex-child"></div>
  <div class="flex-child"></div>
  <div class="flex-child"></div>
</div>
```

```css
.flex-container {
  border: 1px solid red;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.flex-child {
  border: 1px solid blue;
  display: flex;
  height: 100%; 
}
```

`.flex-child` appears collapsed when using percentage based height and `.flex-container` has it's   `flex-direction` set to `column`.

My workaround was to not use `flex-direction` and do the following:

```css
.flex-container {
  border: 1px solid red;
  display: flex;
  flex-wrap: wrap;
  overflow: hidden;
}

.flex-child {
  border: 1px solid blue;
  display: flex;
  height: 100%; 
  width: 100%;
}
```
Curious if this is a known bug or something new.
