### ISSUE TITLE
Flexbug #6 appears to be two-fold

### ISSUE THREAD

**Issue by silvenon** [philipwalton/flexbugs#83]
1.) The initial flex value in IE11 is `none` (`0 0 auto`) instead of `initial` (`0 1 auto`). Nothing much we can do about that except maybe setting `flex` to `0 1 auto` globally? Anyway, when you set `flex` explicitly to `none`, it is interpreted as `0 0 auto` by all browsers except for IE10 who doesn't get the `flex` property (and I'm pretty sure `-ms-flex` doesn't exist). But autoprefixer prefixes that correctly for IE10:

```css
.col {
  -ms-flex-positive: 0;
  -ms-flex-negative: 0;
  -ms-flex-preferred-size: auto;
}
  ```

Whew, that was hard to explain :sweat: 

2.) When `flex-shrink` is not explicitly set in a `flex` declaration, it defaults to `0` instead of `1`. That's a bug that we can fix.
