### ISSUE TITLE
IE 10-11 ignore `flex` shorthand declarations that use `calc`.

### ISSUE THREAD

**Issue by philipwalton** [philipwalton/flexbugs#9]
This can be worked-around by not using the shorthand if you need to use calc. For example:

```css
.FlexItem {
  flex-grow: 0;
  flex-shrink: 0;
  flex-basis: calc(100%/3);
}
```
