### ISSUE TITLE
align-items/content does not work on a container in IE10/11

### ISSUE THREAD

**Issue by simonsmith** [philipwalton/flexbugs#99]
Given this code:

``` css
.FlexContainer {
  min-height: 100px;
  background-color: #ddd;
  display: flex;
  align-items: flex-end;
}

.FlexItem {
  background-color: #bbb;
  flex: 0 1 auto; /* set default for IE10 */
}
```

I expect the items to be aligned along the bottom of the container:

<img width="228" alt="screen shot 2015-11-11 at 13 51 06" src="https://cloud.githubusercontent.com/assets/360703/11092756/8bf901d2-887d-11e5-90e9-840ec2c16095.png">

However in IE10 and 11 it doesn't seem to respect it

<img width="252" alt="screen shot 2015-11-11 at 13 51 27" src="https://cloud.githubusercontent.com/assets/360703/11092764/985146ba-887d-11e5-81bf-c34b39ff70e5.png">

This bug seems too fundamental to be real, am I doing something incorrect here as it also effects `align-content` too.

Not found a workaround at this time.

Pen - http://codepen.io/simonsmith/pen/meQGmN?editors=110
